export interface Car {
  id: number
  brand: string
  model: string
  price: number
  image: string
  category: string
  badge?: string
  year: number
  engine: string
  transmission: string
  drivetrain: string
  power: number
  torque: number
  topSpeed: number
  acceleration: number
  fuel: string
  weight: number
}

export const carsData: Car[] = [
  {
    id: 1,
    brand: "Lamborghini",
    model: "Aventador SVJ",
    price: 573966,
    image: "/assets/cars/lamborghini-aventador.jpg",
    category: "supercar",
    badge: "New Arrival",
    year: 2024,
    engine: "6.5L V12",
    transmission: "7-Speed ISR",
    drivetrain: "AWD",
    power: 770,
    torque: 531,
    topSpeed: 217,
    acceleration: 2.8,
    fuel: "12 mpg",
    weight: 3362
  },
  {
    id: 2,
    brand: "Porsche",
    model: "911 Turbo S",
    price: 216100,
    image: "/assets/cars/porsche-911.jpg",
    category: "sports",
    year: 2024,
    engine: "3.8L Twin-Turbo Flat-6",
    transmission: "8-Speed PDK",
    drivetrain: "AWD",
    power: 640,
    torque: 590,
    topSpeed: 205,
    acceleration: 2.6,
    fuel: "17 mpg",
    weight: 3636
  },
  {
    id: 3,
    brand: "Rolls Royce",
    model: "Spectre",
    price: 420000,
    image: "/assets/cars/rolls-royce-spectre.jpg",
    category: "electric",
    badge: "Electric",
    year: 2024,
    engine: "Dual Electric Motors",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    power: 577,
    torque: 664,
    topSpeed: 155,
    acceleration: 4.4,
    fuel: "Electric - 260mi range",
    weight: 6559
  },
  {
    id: 4,
    brand: "Mercedes-AMG",
    model: "GT 63 S",
    price: 179000,
    image: "/assets/cars/mercedes-amg-gt.jpg",
    category: "sports",
    year: 2024,
    engine: "4.0L Twin-Turbo V8",
    transmission: "9-Speed AMG",
    drivetrain: "AWD",
    power: 630,
    torque: 664,
    topSpeed: 196,
    acceleration: 3.1,
    fuel: "16 mpg",
    weight: 4550
  },
  {
    id: 5,
    brand: "Ferrari",
    model: "SF90 Stradale",
    price: 625000,
    image: "/assets/cars/ferrari-sf90.jpg",
    category: "supercar",
    badge: "Exclusive",
    year: 2024,
    engine: "4.0L Twin-Turbo V8 + 3 Electric Motors",
    transmission: "8-Speed F1 DCT",
    drivetrain: "AWD",
    power: 986,
    torque: 590,
    topSpeed: 211,
    acceleration: 2.5,
    fuel: "16 mpg (Hybrid)",
    weight: 3461
  },
  {
    id: 6,
    brand: "Bentley",
    model: "Continental GT",
    price: 245000,
    image: "/assets/cars/rolls-royce-spectre.jpg",
    category: "luxury",
    badge: "Premium",
    year: 2024,
    engine: "6.0L Twin-Turbo W12",
    transmission: "8-Speed DCT",
    drivetrain: "AWD",
    power: 650,
    torque: 664,
    topSpeed: 208,
    acceleration: 3.5,
    fuel: "14 mpg",
    weight: 5005
  },
  {
    id: 7,
    brand: "McLaren",
    model: "720S Spider",
    price: 315000,
    image: "/assets/cars/lamborghini-aventador.jpg",
    category: "supercar",
    year: 2024,
    engine: "4.0L Twin-Turbo V8",
    transmission: "7-Speed SSG",
    drivetrain: "RWD",
    power: 710,
    torque: 568,
    topSpeed: 212,
    acceleration: 2.8,
    fuel: "18 mpg",
    weight: 3128
  },
  {
    id: 8,
    brand: "Aston Martin",
    model: "DB12 Volante",
    price: 249000,
    image: "/assets/cars/mercedes-amg-gt.jpg",
    category: "sports",
    badge: "2024",
    year: 2024,
    engine: "4.0L Twin-Turbo V8",
    transmission: "8-Speed Auto",
    drivetrain: "RWD",
    power: 671,
    torque: 590,
    topSpeed: 202,
    acceleration: 3.6,
    fuel: "20 mpg",
    weight: 3990
  },
  {
    id: 9,
    brand: "Porsche",
    model: "Taycan Turbo S",
    price: 185000,
    image: "/assets/cars/porsche-911.jpg",
    category: "electric",
    badge: "Electric",
    year: 2024,
    engine: "Dual Electric Motors",
    transmission: "2-Speed Auto",
    drivetrain: "AWD",
    power: 750,
    torque: 774,
    topSpeed: 162,
    acceleration: 2.4,
    fuel: "Electric - 280mi range",
    weight: 5132
  },
  {
    id: 10,
    brand: "Bugatti",
    model: "Chiron Super Sport",
    price: 3900000,
    image: "/assets/cars/ferrari-sf90.jpg",
    category: "supercar",
    badge: "Ultra Rare",
    year: 2024,
    engine: "8.0L Quad-Turbo W16",
    transmission: "7-Speed DCT",
    drivetrain: "AWD",
    power: 1578,
    torque: 1180,
    topSpeed: 273,
    acceleration: 2.3,
    fuel: "8 mpg",
    weight: 4400
  },
  {
    id: 11,
    brand: "Ferrari",
    model: "296 GTB",
    price: 351000,
    image: "/assets/cars/ferrari-sf90.jpg",
    category: "supercar",
    badge: "Hybrid",
    year: 2024,
    engine: "3.0L Twin-Turbo V6 Hybrid",
    transmission: "8-Speed F1 DCT",
    drivetrain: "RWD",
    power: 819,
    torque: 546,
    topSpeed: 205,
    acceleration: 2.9,
    fuel: "18 mpg (Hybrid)",
    weight: 3241
  },
  {
    id: 12,
    brand: "Lamborghini",
    model: "Huracan Tecnica",
    price: 239000,
    image: "/assets/cars/lamborghini-aventador.jpg",
    category: "supercar",
    year: 2024,
    engine: "5.2L V10",
    transmission: "7-Speed DCT",
    drivetrain: "RWD",
    power: 631,
    torque: 417,
    topSpeed: 202,
    acceleration: 3.2,
    fuel: "14 mpg",
    weight: 3313
  }
]
